##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: MutantChallenge
  devtools:
    add-properties: false
  profiles:
    include:
    
dynamodb:
  endpoint: http://localhost:8000
  tbl-name:
    mutant: MutantCheck

